name: Update Cert

on:  
  push:
    branches:
      - main
  schedule:
    - cron: '0 10 1 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Prepare Environment
        run: |
          curl https://get.acme.sh | sh -s email=2675699284@qq.com
          pip install -r requirements.txt
          

      - name: Update Cert
        env:
          CF_Email: ${{ secrets.CF_Email }}
          CF_Key: ${{ secrets.CF_Key }}
          ACME_DNS_TYPE: ${{ secrets.ACME_DNS_TYPE }}
          ACME_DOMAIN: ${{ secrets.ACME_DOMAIN }}
          SECRETID: ${{ secrets.SECRETID }}
          SECRETKEY: ${{ secrets.SECRETKEY }}
          CDN_DOMAIN: ${{ secrets.CDN_DOMAIN }}
          CERT_HOME: /home/runner/.acme.sh
          ACME_HOME: /home/runner/.acme.sh
          WORK_DIR: .
        run: sh ./docker/update.sh
        
